version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    restart: unless-stopped
    ports:
      - "${APP_PORT}:${APP_PORT}"
    env_file:
      - .env
    environment:
      APP_ENV: ${APP_ENV}
      PORT: ${APP_PORT}

      DATABASE_HOST: postgres-database-1
      DATABASE_PORT: "5432"
      DATABASE_NAME: postgres
      DATABASE_USER: postgres
      DATABASE_PASSWORD: sinau123
      DATABASE_MAX_OPEN_CONNECTIONS: ${DATABASE_MAX_OPEN_CONNECTIONS}
      DATABASE_MAX_IDLE_CONNECTIONS: ${DATABASE_MAX_IDLE_CONNECTIONS}

      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_ISSUER: ${JWT_ISSUER}
      JWT_TOKEN_DURATION: ${JWT_TOKEN_DURATION}

      CLOUDFLARE_R2_BUCKET_NAME: ${CLOUDFLARE_R2_BUCKET_NAME}
      CLOUDFLARE_R2_API_KEY: ${CLOUDFLARE_R2_API_KEY}
      CLOUDFLARE_R2_API_SECRET: ${CLOUDFLARE_R2_API_SECRET}
      CLOUDFLARE_R2_TOKEN: ${CLOUDFLARE_R2_TOKEN}
      CLOUDFLARE_R2_ACCOUNT_ID: ${CLOUDFLARE_R2_ACCOUNT_ID}
      CLOUDFLARE_R2_PUBLIC_URL: ${CLOUDFLARE_R2_PUBLIC_URL}

      FRONTEND_URL: ${FRONTEND_URL}

    networks:
      - blueprint
networks:
  blueprint:
